"""
Generates src/data/landPoints.json — a grid of points that fall on actual
land within theaterMap.json's projected geography. Used by
andrewContracts.js so Andrew's contract markers sit on the visible
continent instead of scattering across open ocean.

Run from this directory after theaterMap.json has been (re)generated by
process.py + project.py:

    python landpoints.py
    cp landPoints.json ../src/data/landPoints.json
"""
import json
from shapely.geometry import shape, Point, Polygon
from shapely.ops import unary_union

with open('../src/data/theaterMap.json') as f:
    data = json.load(f)


def parse_path_to_coords(d):
    tokens = d.replace(',', ' ').split()
    pts = []
    i = 0
    while i < len(tokens):
        if tokens[i] in ('M', 'L'):
            pts.append((float(tokens[i + 1]), float(tokens[i + 2])))
            i += 3
        elif tokens[i] == 'Z':
            i += 1
        else:
            i += 1
    return pts


polys = []
for c in data['countries']:
    for p in c['paths']:
        coords = parse_path_to_coords(p)
        if len(coords) >= 3:
            try:
                poly = Polygon(coords)
                if poly.is_valid and poly.area > 0:
                    polys.append(poly)
            except Exception:
                pass

land = unary_union(polys)
print('Land union built, bounds:', land.bounds)

GRID_STEP = 12  # px in the 1000x880 canvas
valid_points = []
for x in range(0, 1001, GRID_STEP):
    for y in range(0, 881, GRID_STEP):
        if land.contains(Point(x, y)):
            valid_points.append((x, y))

print('Valid land points at step', GRID_STEP, ':', len(valid_points))

with open('landPoints.json', 'w') as f:
    json.dump(valid_points, f, separators=(',', ':'))

import os
print('Saved landPoints.json,', os.path.getsize('landPoints.json'), 'bytes')
print('Copy it to ../src/data/landPoints.json to use it.')
